version: '3.1'
services:
  db:
    image: seidakhmet/mysql:8-debian
    build: 
      context: ./db
      dockerfile: Dockerfile
    container_name: "${CONTAINER_NAME}"
    # command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    volumes:
      - ~/database/mysql:/var/lib/mysql
